name: Pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Create Env"
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
        if: success()

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v18.18.1
        if: success()

      - name: Get node_modules cache
        uses: actions/cache@v3
        id: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}-${{ steps.node.outputs.version }}
        if: success()

      - name: Install Dependencies
        run: npm install
        if: success()

      - name: Run Prettier
        run: npm run format
        if: success()

      - name: Run ESLint
        run: npm run lint
        if: success()

      #- name: Build
      #run: npm run build
      #if: success()

      #- name: Deploy
      #  run: npx netlify-cli deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod
      #  if: success() && github.event_name != 'push'
